### PR TITLE
Update Caliper version

### PR DESCRIPTION
**Pull request by andrew-gardener**
Should wait until until next `caliper-php` release (which will include the resource management profile)

Related to https://github.com/ubc/mediawiki-extensions-caliper/pull/1

### CODE REVIEW

**Review by xcompass — APPROVED** [review]

**Comment by xcompass** [comment]
@andrew-gardener is the new caliper-php released? Is this ready to be merged?

**Comment by andrew-gardener** [comment]
the caliper-php library hasn't released yet (though the current develop branch is basically there). I think its alright to hold off merging for now (I'll also need to take a bit of time to test if it works the same with the recent ldap changes)

**Comment by andrew-gardener** [comment]
sorry its taking so long to get this finished >_<"

**Comment by xcompass** [comment]
No worries. Just checking

**Pull request closed without merging**
